name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "COSMOS_DB_ENDPOINT=${{ secrets.AZURE_COSMOSDB_ENDPOINT  }}" >> $GITHUB_ENV
        echo "COSMOS_DB_KEY=${{ secrets.AZURE_COSMOSDB_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      env:
        COSMOSDB_ENDPOINT: ${{ secrets.AZURE_COSMOSDB_ENDPOINT }}
        COSMOSDB_KEY: ${{ secrets.AZURE_COSMOSDB_KEY }}
      run: |
        cd MyFunctions/tests
        pytest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group classshezana--template-file Infrastructure/merged-template.json --parameters Infrastructure/merged-parameters.json
