name: CI

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-functions azure-cosmos

    - name: Set environment variables
      env:
        AZURE_COSMOSDB_KEY: ${{ secrets.AZURE_COSMOSDB_KEY }}
        AZURE_COSMOSDB_ENDPOINT: ${{ secrets.AZURE_COSMOSDB_ENDPOINT }}
      run: echo "Environment variables set."

    - name: Run tests
      env:
        AZURE_COSMOSDB_KEY: ${{ secrets.AZURE_COSMOSDB_KEY }}
        AZURE_COSMOSDB_ENDPOINT: ${{ secrets.AZURE_COSMOSDB_ENDPOINT }}
      run: |
        cd MyFunction
        pytest  # Add any necessary options for pytest

  # Optional: Add a deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run this after the build job succeeds
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Deploy to Azure Function
      env:
        AZURE_FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this secret contains the full JSON credentials
      run: |
        func azure functionapp publish $AZURE_FUNCTION_APP_NAME --python

