name: CI/CD for Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (if required)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MyFunction/requirements.txt  # Adjust if necessary

    # Step 4: Azure CLI Login
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_STUDENT }}  # Use the correct Azure credentials secret

    # Step 5: List files in current directory for debugging
    - name: List files in current directory
      run: ls -R

    # Step 6: Create ZIP package with error handling
    - name: Create ZIP package
      run: |
        zip -r MyFunction.zip MyFunction/ Infrastructure/ || { echo "Failed to create zip"; exit 1; }

    # Step 7: Deploy to Azure Function App
    - name: Deploy to Azure Function App
      run: |
        az functionapp deployment source config-zip \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
          --src MyFunction.zip

    # Step 8: Purge Azure CDN (if needed)
    - name: Purge Azure CDN
      run: |
        az cdn endpoint purge \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --profile-name ${{ secrets.AZURE_CDN_PROFILE }} \
          --name ${{ secrets.AZURE_CDN_ENDPOINT }} \
          --content-paths '/*'
