name: CI/CD Pipeline for MyFunctionApp

# Trigger this pipeline on every push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs that this pipeline will run
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Adjust this based on your project requirements

      # Step 3: Install dependencies from requirements.txt in MyFunction folder
      - name: Install dependencies
        run: pip install -r MyFunction/requirements.txt  # Update the path to MyFunction folder

      # Step 4: Run tests using pytest
      - name: Run Tests
        env:
          AZURE_COSMOSDB_ENDPOINT: ${{ secrets.AZURE_COSMOSDB_ENDPOINT }}  # Use your Azure Cosmos DB endpoint from GitHub secrets
          AZURE_COSMOSDB_KEY: ${{ secrets.AZURE_COSMOSDB_KEY }}  # Use your Azure Cosmos DB key from GitHub secrets
        run: |
          if [ -f MyFunction/test/test_function_app.py ]; then
            pytest MyFunction/test/test_function_app.py;
          else
            echo "No test file found, skipping tests.";
          fi

      # Step 5: Set up Azure CLI for deployment using Student credentials
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STUDENT }}  # Use your Azure credentials for the student subscription

      # Step 6: Deploy to Azure Functions
      - name: Deploy to Azure Functions
        run: |
          az functionapp deployment source config-zip \
          --resource-group classshezana \  # Your resource group for the Azure Function
          --name http_triggershez \  # Your function app name
          --src-path MyFunction/  # Path to your function app directory

      # Step 7: Purge Azure CDN (using Pay-As-You-Go credentials)
      - name: Purge Azure CDN
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS_PAYG.appId }} -p ${{ secrets.AZURE_CREDENTIALS_PAYG.password }} --tenant ${{ secrets.AZURE_CREDENTIALS_PAYG.tenant }}  # Login using Pay-As-You-Go credentials
          az cdn endpoint purge \
          --resource-group 'Team SRE' \  # Your resource group for the CDN
          --profile-name shezana-cdn \  # Your CDN profile name
          --name shezana-end \  # Your CDN endpoint name
          --content-paths "/*"
